run tests for all rv32ui-p-*

diff --git a/core/Makefile b/core/Makefile
--- a/core/Makefile
+++ b/core/Makefile
@@ -4,6 +4,8 @@ clean:
 TARGET  :=
 MEMORY_HEX  := ../hexs/rv32ui-p-add.hex
 
+HEXS    := $(shell ls ../hexs/*)
+
 ifeq ($(TARGET), tiny_rv)
     REQUIRE_MODULES := fetch.v integer_register.v integer_arithmetic_logic.v control_status_registers.v
 endif
@@ -16,6 +18,18 @@ ifeq ($(TARGET), test_system)
     REQUIRE_MODULES := tiny_rv.v fetch.v integer_register.v integer_arithmetic_logic.v dummy_arbiter.v dummy_memory.v opcode_system.v
 endif
 
+riscv-test: FORCE
+	for hex in $(HEXS); do \
+        make TARGET=test_system MEMORY_HEX=$$hex veri; if [ $$? -eq 0 ]; then \
+            echo "[ passed ] $$hex" >> result; \
+        else \
+            echo "[ failed ] $$hex" >> result; \
+        fi \
+	done
+	cat result
+
 ifdef TARGET
     include ../build.mk
+else
+FORCE:
 endif
