restart this project

diff --git a/core/Makefile b/core/Makefile
--- a/core/Makefile
+++ b/core/Makefile
@@ -6,32 +6,24 @@ MEMORY_HEX  := ../hexs/rv32ui-p-add.hex
 
 HEXS    := $(shell ls ../hexs/*)
 
+ifeq ($(TARGET), csr_manager)
+    REQUIRE_MODULES := control_status_registers.v
+endif
+
 ifeq ($(TARGET), tiny_rv)
-    REQUIRE_MODULES := fetch.v integer_register.v integer_arithmetic_logic.v control_status_registers.v
+    REQUIRE_MODULES := fetch.v integer_register.v integer_arithmetic_logic.v control_status_registers.v csr_manager.v
 endif
 
-ifeq ($(TARGET), dummy_arbiter)
-    REQUIRE_MODULES := dummy_memory.v
-endif
-
-ifeq ($(TARGET), test_system)
-    REQUIRE_MODULES := tiny_rv.v fetch.v integer_register.v integer_arithmetic_logic.v dummy_arbiter.v dummy_memory.v opcode_system.v bootrom.v
-endif
-
-ifeq ($(TARGET), arbiter)
-    REQUIRE_MODULES := arbiter.v ../nsl_axi4_lite/axi4_lite_master.v
-endif
-
-riscv-test: FORCE
-	echo '' > riscv_test_result
-	for hex in $(HEXS); do \
-        make TARGET=test_system MEMORY_HEX=$$hex veri; if [ $$? -eq 0 ]; then \
-            echo "[ passed ] $$hex" >> riscv_test_result; \
-        else \
-            echo "[ failed ] $$hex" >> riscv_test_result; \
-        fi \
-	done
-	cat riscv_test_result
+#riscv-test: FORCE
+#	echo '' > riscv_test_result
+#	for hex in $(HEXS); do \
+#        make TARGET=test_system MEMORY_HEX=$$hex veri; if [ $$? -eq 0 ]; then \
+#            echo "[ passed ] $$hex" >> riscv_test_result; \
+#        else \
+#            echo "[ failed ] $$hex" >> riscv_test_result; \
+#        fi \
+#	done
+#	cat riscv_test_result
 
 ifdef TARGET
     include ../build.mk
